# This is a TOML document about the abbreviations of common file type.
[file_type]
css=["cascading style sheets"]
doc=["document"]
docx=["document xml"]
exe=["executable file"]
html=["hyper text markup language"]
ppt=["powerpoint"]
pptx=["powerpoint xml"]
pdf=["portable document format"]
rtf=["rich text format"]
txt=["text"]
xml=["extensible markup language"]
xls=["excel spreadsheet"]
xlsx=["excel spreadsheet xml"]
svg=["scalable vector graphic"]
img=["image"]
png=["portable network graphics"]
jpeg=["joint photographic experts group"]
jpg=["joint photographic experts group"]
gif=["graphics interchange format"]
bmp=["bitmap"]
ico=["icon"]
yml=["yaml"]
md=["markdown"]
