# This is a TOML document about the number abbreviations.
[number]
bin=["binary"]
oct=["octal"]
dec=["decimal"]
duo=["duodecimal"]
hex=["hexadecimal"]
1rt=["first"]
2nd=["second"]
3rd=["third"]
4th=["fourth"]
5th=["fifth"]
6th=["sixth"]
7th=["seventh"]
8th=["eighth"]
9th=["ninth"]
10th=["tenth"]
fst=["first"]
snd=["second"]
trd=["third"]
frth=["fourth"]
fth=["fifth"]
sth=["sixth"]
svnth=["seventh"]
eth=["eighth"]
nth=["ninth"]
tth=["tenth"]