[b]
beg=["begin"]
bg=["background"]
biz=["business"]
bld=["build"]
bldg=["building"]
blk=["block"]
brk=["break"]
bk=["back"]
btm=["bottom"]
btn=["button"]
buf=["buffer"]
btw=["between"]
bg=["background"]