[b]
b=["bit"]
bat=["batch"]
beg=["begin"]
bench=["benchmark"]
bg=["background"]
bin=["binary"]
biz=["business"]
bk=["back"]
blk=["block"]
bld=["build"]
blding=["building"]
bool=["boolean"]
brd=["broadcast"]
brk=["break"]
buf=["buffer"]
btn=["button"]
btm=["bottom"]
btw=["between"]