[c]
cal=["calendar"]
calc=["calculate","calculation"]
can=["cancel"]
cap=["capacity"]
cas=["compare and swap"]
cate=["category"]
cfg=["config","configuration"]
chg=["change"]
chan=["channel"]
char=["character"]
chk=["check"]
chld=["child"]
cld=["cloud"]
cli=["command line interface"]
clk=["click","clock"]
clr=["clear","color"]
clt=["client"]
cmd=["command"]
cmp=["compare"]
cnt=["count"]
col=["column"]
coll=["collection"]
comm=["common","communication"]
comp=["company"]
concat=["concatenate"]
con=["const"]
concur=["concurrency","concurrent"]
cond=["condition"]
conf=["config","configuration"]
confl=["conflict"]
conn=["connection"]
cons=["construct"]
cont=["content","continue"]
contr=["contract","contraction"]
conv=["convert","conversion"]
coord=["coordinate"]
cp=["couple"]
cpl=["complete"]
cpy=["copy"]
crt=["create","correct","court"]
csm=["consumer"]
csr=["cursor"]
ctr=["counter"]
ctrl=["control","controller"]
ctx=["context"]
cum=["cumulative"]
cur=["current"]
cyl=["cylinder"]