[f]
fd=["file descriptor"]
fea=["feature"]
fi=["finance"]
fin=["finish"]
fld=["field"]
flg=["flag"]
flt=["fault"]
fmt=["format"]
fpe=["floating-point exception"]
freq=["frequency"]
frm=["frame"]
fract=["fraction"]
ful=["full"]