[f]
fav=["favorite"]
fd=["file descriptor"]
feat=["feature"]
fin=["finance", "finish"]
fld=["field"]
flg=["flag"]
flt=["fault"]
fmt=["format"]
fpe=["floating-point exception"]
freq=["frequency"]
frm=["form", "frame"]
fract=["fraction"]
ful=["full"]
fg=["foreground"]