[i]
id=["identity","identifier"]
idx=["index"]
ill=["illegal"]
impl=["implement"]
in=["input"]
inc=["incorporation"]
incl=["include"]
incr=["increase","increment"]
ineff=["ineffective"]
info=["infomation"]
init=["initiation","initialization"]
ins=["instance","insert"]
int=["interrupt"]
intro=["introduction"]
intvl=["interval"]
invld=["invalid"]
invt=["invert"]
instr=["instruction"]
impt=["important"]