[i]
id=["identifier"]
idx=["index"]
incr=["increment","increase"]
ineff=["ineffective"]
info=["infomation"]
in=["input"]
img=["image"]
imp=["implement"]
init=["initialization"]
isrt=["insert"]
ins=["instance"]
istr=["instruction"]
intr=["interrupt"]
intv=["interval"]
inv=["invalid"]
invt=["invert"]