[i]
id=["identifier"]
idx=["index"]
imp=["implement"]
in=["input"]
incr=["increment","increase"]
ineff=["ineffective"]
info=["infomation"]
init=["initiation","initialization"]
ins=["instance","insert"]
intr=["interrupt"]
intro=["introduction"]
intvl=["interval"]
inv=["invalid"]
invt=["invert"]
instr=["instruction"]