[l]
lang=["language"]
lbl=["label"]
le=["less equal"]
len=["length"]
lgc=["logic"]
lhs=["left-hand side"]
lib=["library"]
lmt=["limit"]
lmter=["limiter"]
lit=["literal"]
lck=["lock"]
lnk=["link"]
lo=["low"]
lst=["list"]
lt=["less than"]