[l]
lang=["language"]
lbl=["label"]
le=["less equal"]
len=["length"]
lgc=["logic"]
lib=["library"]
lim=["limit","limiter"]
lit=["literal"]
lk=["lock"]
lnk=["link"]
lo=["low"]
lst=["list"]
lt=["less than"]