[o]
o=["output"]
obj=["object"]
ofs=["offset"]
op=["operate","operating","operated"]
oper=["operator"]
opt=["optimize","optimization","option","optional"]
ops=["operations"]
org=["origin","organization"]
ovf=["overflow"]