[p]
pass=["password"]
param=["parameter"]
pct=["percentile"]
perf=["performance"]
perd=["period"]
permut=["permutation"]
perm=["permit","permission"]
pkg=["package"]
pkt=["packet"]
psh=["push"]
ptn=["partition"]
pic=["picture"]
pt=["point"]
ptr=["pointer"]
pos=["position","positive"]
pwr=["power"]
pre=["prefix","previous","preview"]
prec=["precision"]
press=["pressure"]
prt=["print"]
prv=["private"]
prio=["priority"]
proc=["process"]
prod=["product"]
prof=["profile"]
pprof=["performance profiling"]
proj=["project"]
prg=["program"]
prop=["property"]
proto=["protocol"]
prot=["protect"]
prx=["proxy"]
pub=["public"]