[p]
pass=["password"]
param=["parameter"]
pct=["percent","percentile"]
perf=["performance"]
perd=["period"]
perm=["permit","permission"]
permut=["permutation"]
pic=["picture"]
pkg=["package"]
pkt=["packet"]
pls=["please"]
pos=["position","positive"]
pprof=["performance profiling"]
pre=["prefix"]
prec=["precision"]
prep=["prepare","preparation"]
press=["pressure"]
prev=["previous","preview"]
prg=["program"]
prt=["print"]
prv=["private"]
pri=["priority"]
proc=["process"]
prod=["product","production"]
prof=["profile"]
proj=["project"]
prom=["prometheus"]
prop=["property"]
proto=["protocol"]
prot=["protect","protection"]
prx=["proxy"]
psh=["push"]
ptn=["partition"]
pt=["point"]
ptr=["pointer"]
pub=["public"]
pwr=["power"]