[p]
pass=["password"]
param=["parameter"]
pct=["percent","percentile"]
perf=["performance"]
perd=["period"]
perm=["permit","permission"]
permut=["permutation"]
pic=["picture"]
pkg=["package"]
pkt=["packet"]
pos=["position","positive"]
pprof=["performance profiling"]
pre=["prefix","previous","preview"]
prec=["precision"]
prep=["prepare","preparation"]
press=["pressure"]
prt=["print"]
prv=["private"]
prio=["priority"]
proc=["process"]
prod=["product"]
prof=["profile"]
proj=["project"]
prg=["program"]
prop=["property"]
proto=["protocol"]
prot=["protect"]
prx=["proxy"]
psh=["push"]
ptn=["partition"]
pt=["point"]
ptr=["pointer"]
pub=["public"]
pwr=["power"]