[r]
r=["read"]
rand=["random"]
rat=["rational"]
rcl=["recall"]
rdy=["ready"]
react=["reactive"]
rec=["record"]
recv=["receive"]
rect=["rectangle"]
recu=["recursion"]
ref=["reference"]
reg=["register"]
rel=["release"]
rep=["replication"]
repo=["repository"]
req=["request","require"]
res=["resource","result"]
resv=["reserve"]
resu=["resume"]
ret=["return"]
rev=["reverse"]
rgn=["region"]
rm=["remove"]
rpt=["repeat"]
rst=["reset"]
rsp=["response"]