[r]
r=["read"]
rand=["random"]
rat=["rational"]
rcl=["recall"]
rcmd=["recommend"]
rdy=["ready"]
rds=["redis"]
react=["reactive"]
rec=["record"]
recv=["receive"]
rect=["rectangle"]
recu=["recursion"]
ref=["reference"]
reg=["register"]
regexp=["regular expression"]
rel=["relative"]
repl=["replicate","replication"]
repo=["repository"]
req=["request","require"]
res=["resource"]
resv=["reserve"]
resu=["resume"]
ret=["return"]
rev=["reverse"]
rgn=["region"]
rhs=["right-hand side"]
rls=["release"]
rm=["remove"]
rpt=["repeat"]
rslt=["result"]
rst=["reset"]
rsp=["response"]