[r]
r=["read"]
rand=["random"]
rm=["remove"]
rcl=["recall"]
rdy=["ready"]
react=["reactive"]
rec=["record"]
recv=["receive"]
rect=["rectangle"]
recu=["recursion"]
ref=["reference"]
reg=["register"]
rgn=["region"]
rel=["release"]
rpt=["repeat"]
repo=["repository"]
req=["request","require"]
resv=["reserve"]
rst=["reset"]
res=["resource","result"]
rsp=["response"]
resu=["resume"]
ret=["return"]
rev=["reverse"]