[s]
smp=["sample"]
scal=["scale"]
sca=["scan"]
sch=["schedule"]
sched=["scheduler"]
scr=["screen"]
srch=["search"]
sec=["second"]
sect=["section"]
seg=["segment"]
sel=["select"]
sem=["semaphore"]
seq=["sequence"]
svr=["server"]
seri=["serialize"]
sig=["signal"]
src=["source"]
spec=["specification"]
std=["standard"]
stat=["status","statistic"]
stg=["storage"]
stra=["strategy"]
struc=["structure"]
stm=["stream"]
subs=["subscribe"]
sub=["subtract"]
sum=["summation"]
succ=["success"]
susp=["suspend"]
sw=["switch"]
sync=["synchronization"]
sys=["system"]