[s]
scal=["scale"]
sca=["scan"]
sch=["schedule"]
sched=["scheduler"]
scr=["screen"]
srch=["search"]
sec=["second"]
sect=["section"]
seg=["segment"]
sel=["select"]
sem=["semaphore"]
seq=["sequence"]
seri=["serialize"]
sgl=["single"]
sig=["signal"]
smp=["sample"]
snd=["send"]
src=["source"]
spec=["specification"]
std=["standard"]
stu=["student"]
stat=["status","statistic"]
stg=["storage"]
stmt=["statement"]
stra=["strategy"]
struc=["structure"]
stm=["stream"]
subs=["subscribe"]
sub=["subtract"]
suf=["suffix"]
sum=["summation","summary"]
succ=["success"]
susp=["suspend"]
svr=["server"]
sw=["switch"]
sync=["synchronization","synchronize"]
sys=["system"]