[s]
scal=["scale"]
sca=["scan"]
sched=["schedule"]
scheder=["scheduler"]
scr=["screen"]
sec=["second"]
sect=["section"]
seg=["segment"]
segv=["segmentation violation"]
sel=["select"]
sem=["semaphore"]
seq=["sequence"]
seri=["serialize"]
sess=["session"]
sgl=["single"]
sig=["signal"]
smp=["sample"]
snd=["send"]
spec=["specification"]
src=["source"]
srch=["search"]
srv=["serve"]
std=["standard"]
stu=["student"]
stat=["status","statistic"]
stg=["storage"]
stmt=["statement"]
stm=["stream"]
stp=["stop"]
stra=["strategy"]
struc=["structure"]
subs=["subscribe"]
sub=["subtract"]
suf=["suffix"]
sum=["summation","summary"]
succ=["success"]
susp=["suspend"]
sv=["save"]
svc=["service"]
svr=["server"]
sw=["switch"]
sync=["synchronization","synchronize"]
sys=["system"]
sz=["size"]