[t]
t=["type"]
tbl=["table"]
tgt=["target"]
tgl=["toggle"]
thold=["threshold"]
tmp=["temporary"]
tpl=["template"]
to=["timeout"]
tot=["total"]
tran=["translate"]
trig=["trigger"]
tsk=["task"]
tst=["test"]
ts=["timestamp"]
