[t]
t=["type"]
tbl=["table"]
tech=["technology"]
temp=["temperature"]
term=["termination"]
tgt=["target"]
tgl=["toggle"]
thresh=["threshold"]
thd=["thread"]
tmp=["temporary"]
tmplt=["template"]
to=["timeout"]
tot=["total"]
trans=["translate"]
trig=["trigger"]
tsk=["task"]
tst=["test"]
ts=["timestamp"]
