[t]
t=["type"]
tbl=["table"]
temp=["temperature"]
tgt=["target"]
tgl=["toggle"]
thres=["threshold"]
thrd=["thread"]
tmp=["temporary"]
tpl=["template"]
to=["timeout"]
tot=["total"]
trans=["translate"]
trig=["trigger"]
tsk=["task"]
tst=["test"]
ts=["timestamp"]
