[t]
tgt=["target"]
tbl=["table"]
tsk=["task"]
tmp=["temporary"]
tmpl=["template"]
tst=["test"]
txt=["text"]
thold=["threshold"]
to=["timeout"]
tgl=["toggle"]
tot=["total"]
tran=["translate"]
trig=["trigger"]
ts=["timestamp"]