[t]
tbl=["table"]
tgt=["target"]
tgl=["toggle"]
thold=["threshold"]
tmp=["temporary"]
tmpl=["template"]
to=["timeout"]
tot=["total"]
tran=["translate"]
trig=["trigger"]
tsk=["task"]
tst=["test"]
ts=["timestamp"]
txt=["text"]
